Realización de tarea 6
sergio-ceballos-intelex/tareas-modulo-3-grupo-12 pull request #40
Opened 2024-10-11 16:49 UTC by nandresf23

2024-10-14 02:36 UTC, sergio-ceballos-intelex commented on felipe-naranjo-3108157069/tarea_6/main.js
> +    numeros[i] = numeros[i] * 2;
aqui estas cambiando el valor en el array numeros, seria mejor dejar este array sin modificar y usar para el resultado final el de multiplcar como lo estas haciendo ahora

2024-10-14 02:37 UTC, sergio-ceballos-intelex commented on felipe-naranjo-3108157069/tarea_6/main.js
> +let frutasResultante = frutas1;
a pesar de que la referencia seria la misma para ambos arrays, creo que esta linea no es necesaria, usa directamente frutas1

2024-10-14 02:38 UTC, sergio-ceballos-intelex requested changes
corregir comentarios

2024-10-19 14:05 UTC, nandresf23 commented
comenatrios corregidos

2024-10-22 19:12 UTC, merged